// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: nextra/options.proto

package nextra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorDetailField is a free-form field annotation for an error detail type.
type ErrorDetailField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetailField) Reset() {
	*x = ErrorDetailField{}
	mi := &file_nextra_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetailField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailField) ProtoMessage() {}

func (x *ErrorDetailField) ProtoReflect() protoreflect.Message {
	mi := &file_nextra_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailField.ProtoReflect.Descriptor instead.
func (*ErrorDetailField) Descriptor() ([]byte, []int) {
	return file_nextra_options_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetailField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ErrorDetailField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ErrorDef documents a single error a method may return.
type ErrorDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the gRPC status code name, e.g. "NOT_FOUND".
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// description is a human-readable explanation of when this error occurs.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// detail_type is the fully-qualified proto message name used as the error
	// detail, e.g. "google.rpc.BadRequest" or "myapp.ValidationError".
	DetailType string `protobuf:"bytes,3,opt,name=detail_type,json=detailType,proto3" json:"detail_type,omitempty"`
	// fields provides free-form field annotations for the detail type.
	Fields        []*ErrorDetailField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDef) Reset() {
	*x = ErrorDef{}
	mi := &file_nextra_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDef) ProtoMessage() {}

func (x *ErrorDef) ProtoReflect() protoreflect.Message {
	mi := &file_nextra_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDef.ProtoReflect.Descriptor instead.
func (*ErrorDef) Descriptor() ([]byte, []int) {
	return file_nextra_options_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDef) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ErrorDef) GetDetailType() string {
	if x != nil {
		return x.DetailType
	}
	return ""
}

func (x *ErrorDef) GetFields() []*ErrorDetailField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// MethodErrors lists the errors a method may return.
type MethodErrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ErrorDef            `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodErrors) Reset() {
	*x = MethodErrors{}
	mi := &file_nextra_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodErrors) ProtoMessage() {}

func (x *MethodErrors) ProtoReflect() protoreflect.Message {
	mi := &file_nextra_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodErrors.ProtoReflect.Descriptor instead.
func (*MethodErrors) Descriptor() ([]byte, []int) {
	return file_nextra_options_proto_rawDescGZIP(), []int{2}
}

func (x *MethodErrors) GetErrors() []*ErrorDef {
	if x != nil {
		return x.Errors
	}
	return nil
}

var file_nextra_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50051,
		Name:          "nextra.server_addr",
		Tag:           "bytes,50051,opt,name=server_addr",
		Filename:      "nextra/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodErrors)(nil),
		Field:         50052,
		Name:          "nextra.method_errors",
		Tag:           "bytes,50052,opt,name=method_errors",
		Filename:      "nextra/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// server_addr overrides the default gRPC server address used in the
	// generated usage examples for this specific service.
	//
	// optional string server_addr = 50051;
	E_ServerAddr = &file_nextra_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// method_errors documents the errors a method may return.
	//
	// optional nextra.MethodErrors method_errors = 50052;
	E_MethodErrors = &file_nextra_options_proto_extTypes[1]
)

var File_nextra_options_proto protoreflect.FileDescriptor

const file_nextra_options_proto_rawDesc = "" +
	"\n" +
	"\x14nextra/options.proto\x12\x06nextra\x1a google/protobuf/descriptor.proto\"<\n" +
	"\x10ErrorDetailField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x93\x01\n" +
	"\bErrorDef\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vdetail_type\x18\x03 \x01(\tR\n" +
	"detailType\x120\n" +
	"\x06fields\x18\x04 \x03(\v2\x18.nextra.ErrorDetailFieldR\x06fields\"8\n" +
	"\fMethodErrors\x12(\n" +
	"\x06errors\x18\x01 \x03(\v2\x10.nextra.ErrorDefR\x06errors:B\n" +
	"\vserver_addr\x12\x1f.google.protobuf.ServiceOptions\x18\x83\x87\x03 \x01(\tR\n" +
	"serverAddr:[\n" +
	"\rmethod_errors\x12\x1e.google.protobuf.MethodOptions\x18\x84\x87\x03 \x01(\v2\x14.nextra.MethodErrorsR\fmethodErrorsB3Z1github.com/jamillosantos/protoc-gen-nextra/nextrab\x06proto3"

var (
	file_nextra_options_proto_rawDescOnce sync.Once
	file_nextra_options_proto_rawDescData []byte
)

func file_nextra_options_proto_rawDescGZIP() []byte {
	file_nextra_options_proto_rawDescOnce.Do(func() {
		file_nextra_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nextra_options_proto_rawDesc), len(file_nextra_options_proto_rawDesc)))
	})
	return file_nextra_options_proto_rawDescData
}

var file_nextra_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nextra_options_proto_goTypes = []any{
	(*ErrorDetailField)(nil),            // 0: nextra.ErrorDetailField
	(*ErrorDef)(nil),                    // 1: nextra.ErrorDef
	(*MethodErrors)(nil),                // 2: nextra.MethodErrors
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 4: google.protobuf.MethodOptions
}
var file_nextra_options_proto_depIdxs = []int32{
	0, // 0: nextra.ErrorDef.fields:type_name -> nextra.ErrorDetailField
	1, // 1: nextra.MethodErrors.errors:type_name -> nextra.ErrorDef
	3, // 2: nextra.server_addr:extendee -> google.protobuf.ServiceOptions
	4, // 3: nextra.method_errors:extendee -> google.protobuf.MethodOptions
	2, // 4: nextra.method_errors:type_name -> nextra.MethodErrors
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nextra_options_proto_init() }
func file_nextra_options_proto_init() {
	if File_nextra_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nextra_options_proto_rawDesc), len(file_nextra_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_nextra_options_proto_goTypes,
		DependencyIndexes: file_nextra_options_proto_depIdxs,
		MessageInfos:      file_nextra_options_proto_msgTypes,
		ExtensionInfos:    file_nextra_options_proto_extTypes,
	}.Build()
	File_nextra_options_proto = out.File
	file_nextra_options_proto_goTypes = nil
	file_nextra_options_proto_depIdxs = nil
}
